name: Deploy CI

on:
  push:
    branches:
      - master

env:
  DEBUG: 1
  NODE_ENV: development

jobs:
  deployToAWS:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: NPM install
        shell: bash
        run: npm i --production
      - name: NPM build
        shell: bash
        run: npm run build
      - name: Copy files to S3 with the AWS CLI
        shell: bash
        run: aws s3 sync ./build "s3://${{ secrets.AWS_S3_BUCKET }}"
